name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Auth to dockerhub
      run: docker login -u {{secrets.DOCKERHUB_USERNAME}} -p {{secrets.DOCKERHUB_ACCESS_TOKEN}}
    - name: Build the Docker image
      run: |
        for i in $(cat releases)
        do;
            docker build --rm --build-arg="OPENTTD_VERSION=$i" -t bateau/openttd:$i .;
            docker push bateau/openttd:$i;
        done